name: Publish Firmware

on:
  release:
    types: [published]

jobs:
  build-firmware:
    name: Build Firmware
    uses: esphome/workflows/.github/workflows/build.yml@2024.10.0
    with:
      files: |
        project-template-esp32.factory.yaml
        project-template-esp32-c3.factory.yaml
        project-template-esp32-s3.factory.yaml
      esphome-version: 2024.10.3
      combined-name: firmware
      release-summary: ${{ github.event.release.body }}
      release-url: ${{ github.event.release.html_url }}
      release-version: ${{ github.event.release.tag_name }}

  upload-to-release:
    name: Upload to Release
    needs:
      - build-firmware
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          path: files
      - name: Copy files to output
        run: |-
          mkdir output
          version="${{ needs.build-firmware.outputs.version }}"
          pushd files
          for device in *; do
            pushd $device
            pushd $version
            cp manifest.json ../../../output/$device.manifest.json
            for bin in *.bin; do
              md5sum $bin | head -c 32 > ../../../output/$bin.md5
              cp $bin ../../../output/
            done
            popd
            popd
          done
          popd
      - name: Upload files to release
        uses: softprops/action-gh-release@v2.1.0
        with:
          files: output/*
