name: Publish Firmware

on:
  release:
    types: [published]

jobs:
  build-firmware:
    name: Build Firmware
    uses: esphome/workflows/.github/workflows/build.yml@2024.10.0
    with:
      files: |
        project-template-esp32.factory.yaml
        project-template-esp32-c3.factory.yaml
        project-template-esp32-s3.factory.yaml
      esphome-version: 2024.10.3
      combined-name: firmware
      release-summary: ${{ github.event.release.body }}
      release-url: ${{ github.event.release.html_url }}
      release-version: ${{ github.event.release.tag_name }}

  upload-to-release:
    name: Upload to Release
    uses: esphome/workflows/.github/workflows/upload-to-gh-release.yml@main
    needs:
      - build-firmware
    with:
      version: ${{ github.event.release.tag_name }}"
